# Generated by Django 3.0.3 on 2020-02-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_carousel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel_image',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
