# Generated by Django 3.0.3 on 2020-02-28 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_points'),
    ]

    operations = [
        migrations.DeleteModel(
            name='guess',
        ),
    ]
