# Generated by Django 3.0.3 on 2020-02-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_delete_guess'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='q_ans',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
